namespace Silk.Data.SQL.ORM.Schema
{
	public class Column
	{
		public string ColumnName { get; }
		public SqlDataType SqlDataType { get; }
		public bool IsPrimaryKey { get; }
		public bool IsAutoIncrement { get; }
		public bool IsAutoGenerated { get; }

		public Column(string columnName, SqlDataType sqlDataType,
			bool isPrimaryKey = false, bool isAutoIncrement = false, bool isAutoGenerated = false)
		{
			ColumnName = columnName;
			SqlDataType = sqlDataType;
			IsPrimaryKey = isPrimaryKey;
			IsAutoGenerated = isAutoGenerated;
			IsAutoIncrement = isAutoIncrement;
		}
	}
}